version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    volumes: 
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports: 
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    
  backend:
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
      POSTGRESQL_DB: ${POSTGRESQL_DB}
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXP}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    build: mvp
    depends_on: 
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}



volumes: 
  data: {}
