spring.application.name=mvp
server.port=${SERVER_PORT}

#Import du fichier contenant les variables d'environnement
spring.config.import=file:mvp/env.properties

# Configuration des propriétés de la source de données

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Connexion à la base de données PostGreSQL avec Spring Data JPA

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.jwt-secret=${JWT_SECRET}
app.jwt-expiration-milliseconds=${JWT_EXP}