spring.application.name=mvp

# Configuration des propriétés de la source de données

spring.datasource.url=jdbc:postgresql://localhost:5432/fisor_db
spring.datasource.username=postgreUser
spring.datasource.password=password

# Connexion à la base de données PostGreSQL avec Spring Data JPA

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
spring.jpa.hibernate.ddl-auto=update

